In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/playground-series-s4e11/sample_submission.csv
/kaggle/input/playground-series-s4e11/train.csv
/kaggle/input/playground-series-s4e11/test.csv

check with combining training and testing data combined ie 
data leakage

In [2]:
test_data = pd.read_csv('/kaggle/input/playground-series-s4e11/test.csv')
train_data = pd.read_csv('/kaggle/input/playground-series-s4e11/train.csv')

In [3]:
train_data.head()

,id,Name,Gender,Age,City,Working Professional or Student,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,0,Aaradhya,Female,49.0,Ludhiana,Working Professional,Chef,NaN,5.0,NaN,NaN,2.0,More than 8 hours,Healthy,BHM,No,1.0,2.0,No,0
1,1,Vivan,Male,26.0,Varanasi,Working Professional,Teacher,NaN,4.0,NaN,NaN,3.0,Less than 5 hours,Unhealthy,LLB,Yes,7.0,3.0,No,1
2,2,Yuvraj,Male,33.0,Visakhapatnam,Student,NaN,5.0,NaN,8.97,2.0,NaN,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
3,3,Yuvraj,Male,22.0,Mumbai,Working Professional,Teacher,NaN,5.0,NaN,NaN,1.0,Less than 5 hours,Moderate,BBA,Yes,10.0,1.0,Yes,1
4,4,Rhea,Female,30.0,Kanpur,Working Professional,Business Analyst,NaN,1.0,NaN,NaN,1.0,5-6 hours,Unhealthy,BBA,Yes,9.0,4.0,Yes,0

In [4]:
test_data.head()

,id,Name,Gender,Age,City,Working Professional or Student,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness
0,140700,Shivam,Male,53.0,Visakhapatnam,Working Professional,Judge,NaN,2.0,NaN,NaN,5.0,Less than 5 hours,Moderate,LLB,No,9.0,3.0,Yes
1,140701,Sanya,Female,58.0,Kolkata,Working Professional,Educational Consultant,NaN,2.0,NaN,NaN,4.0,Less than 5 hours,Moderate,B.Ed,No,6.0,4.0,No
2,140702,Yash,Male,53.0,Jaipur,Working Professional,Teacher,NaN,4.0,NaN,NaN,1.0,7-8 hours,Moderate,B.Arch,Yes,12.0,4.0,No
3,140703,Nalini,Female,23.0,Rajkot,Student,NaN,5.0,NaN,6.84,1.0,NaN,More than 8 hours,Moderate,BSc,Yes,10.0,4.0,No
4,140704,Shaurya,Male,47.0,Kalyan,Working Professional,Teacher,NaN,5.0,NaN,NaN,5.0,7-8 hours,Moderate,BCA,Yes,3.0,4.0,No

In [5]:
train_data.describe()

,id,Age,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Work/Study Hours,Financial Stress,Depression
count,140700.000000,140700.000000,27897.000000,112782.000000,27898.000000,27897.000000,112790.000000,140700.000000,140696.000000,140700.000000
mean,70349.500000,40.388621,3.142273,2.998998,7.658636,2.944940,2.974404,6.252679,2.988983,0.181713
std,40616.735775,12.384099,1.380457,1.405771,1.464466,1.360197,1.416078,3.853615,1.413633,0.385609
min,0.000000,18.000000,1.000000,1.000000,5.030000,1.000000,1.000000,0.000000,1.000000,0.000000
25%,35174.750000,29.000000,2.000000,2.000000,6.290000,2.000000,2.000000,3.000000,2.000000,0.000000
50%,70349.500000,42.000000,3.000000,3.000000,7.770000,3.000000,3.000000,6.000000,3.000000,0.000000
75%,105524.250000,51.000000,4.000000,4.000000,8.920000,4.000000,4.000000,10.000000,4.000000,0.000000
max,140699.000000,60.000000,5.000000,5.000000,10.000000,5.000000,5.000000,12.000000,5.000000,1.000000

CGPA tells me all the students

In [6]:
test_data.describe()

,id,Age,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Work/Study Hours,Financial Stress
count,93800.000000,93800.000000,18767.000000,75022.000000,18766.000000,18767.000000,75026.00000,93800.000000,93800.000000
mean,187599.500000,40.321685,3.158576,3.011797,7.674016,2.939522,2.96092,6.247335,2.978763
std,27077.871962,12.393480,1.386666,1.403563,1.465056,1.374242,1.41071,3.858191,1.414604
min,140700.000000,18.000000,1.000000,1.000000,5.030000,1.000000,1.00000,0.000000,1.000000
25%,164149.750000,29.000000,2.000000,2.000000,6.330000,2.000000,2.00000,3.000000,2.000000
50%,187599.500000,42.000000,3.000000,3.000000,7.800000,3.000000,3.00000,6.000000,3.000000
75%,211049.250000,51.000000,4.000000,4.000000,8.940000,4.000000,4.00000,10.000000,4.000000
max,234499.000000,60.000000,5.000000,5.000000,10.000000,5.000000,5.00000,12.000000,5.000000

In [7]:
train_data['Have you ever had suicidal thoughts ?'] = train_data['Have you ever had suicidal thoughts ?'].map({'Yes': 1, 'No': 0})
train_data['Family History of Mental Illness'] = train_data['Family History of Mental Illness'].map({'Yes': 1, 'No': 0})

In [8]:
train_data['Academic Pressure'] = train_data['Academic Pressure'].fillna(0)
train_data['Work Pressure'] = train_data['Work Pressure'].fillna(0)

test_data['Academic Pressure'] = test_data['Academic Pressure'].fillna(0)
test_data['Work Pressure'] = test_data['Work Pressure'].fillna(0)

train_data['Pressure'] = train_data['Academic Pressure'] + train_data['Work Pressure']
test_data['Pressure'] = test_data['Academic Pressure'] + test_data['Work Pressure']

train_data['Pressure'] = train_data['Pressure'].replace(0, 3)
test_data['Pressure'] = test_data['Pressure'].replace(0, 3)

In [9]:
train_data['Study Satisfaction'] = train_data['Study Satisfaction'].fillna(0)
train_data['Job Satisfaction'] = train_data['Work Pressure'].fillna(0)

test_data['Study Satisfaction'] = test_data['Study Satisfaction'].fillna(0)
test_data['Job Satisfaction'] = test_data['Job Satisfaction'].fillna(0)

train_data['Satisfaction'] = train_data['Study Satisfaction'] + train_data['Job Satisfaction']
test_data['Satisfaction'] = test_data['Study Satisfaction'] + test_data['Job Satisfaction']

train_data['Satisfaction'] = train_data['Satisfaction'].replace(0, 3)
test_data['Satisfaction'] = test_data['Satisfaction'].replace(0, 3)

In [10]:
train_data['Financial Stress'] = train_data['Financial Stress'].fillna(2.988983)

In [11]:
train_data['Gender'] = train_data['Gender'].map({'Male': 0, 'Female': 1})
test_data['Gender'] = test_data['Gender'].map({'Male': 0, 'Female': 1})

In [12]:
from sklearn.preprocessing import OrdinalEncoder

# Define the columns you want to encode
object_cols = ['Dietary Habits', 'Sleep Duration']

# Initialize OrdinalEncoder with handling for unknown categories
ordinal_encoder = OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)

# Fit the encoder on the training data and transform
train_data[object_cols] = ordinal_encoder.fit_transform(train_data[object_cols])

# Transform the test data based on the fitted encoder
test_data[object_cols] = ordinal_encoder.transform(test_data[object_cols])

# Check the transformed data
print(train_data[object_cols].head())
print(test_data[object_cols].head())

   Dietary Habits  Sleep Duration
0             7.0            29.0
1            20.0            27.0
2             7.0            15.0
3            15.0            27.0
4            20.0            15.0
   Dietary Habits  Sleep Duration
0            15.0            27.0
1            15.0            27.0
2            15.0            19.0
3            15.0            29.0
4            15.0            19.0

In [13]:
train_data['Sleep Duration'] = train_data['Sleep Duration'].fillna(3)
test_data['Sleep Duration'] = test_data['Sleep Duration'].fillna(3)

In [14]:
train_data['Dietary Habits'] = train_data['Dietary Habits'].fillna(2)
test_data['Dietary Habits'] = test_data['Dietary Habits'].fillna(2)

In [15]:
train_data['Work-Life Balance'] = train_data['Work/Study Hours'] / train_data['Sleep Duration'].replace(0, 1)
test_data['Work-Life Balance'] = test_data['Work/Study Hours'] / test_data['Sleep Duration'].replace(0, 1)

In [16]:
train_data.describe()

,id,Gender,Age,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression,Pressure,Satisfaction,Work-Life Balance
count,140700.000000,140700.000000,140700.000000,140700.000000,140700.000000,27898.000000,140700.000000,140700.000000,140700.000000,140700.000000,140700.000000,140700.000000,140700.000000,140700.000000,140700.000000,140700.000000,140700.000000,140700.000000
mean,70349.500000,0.449439,40.388621,0.623028,2.403930,7.658636,0.583902,2.403930,22.614606,14.097910,0.494399,6.252679,2.988983,0.497100,0.181713,3.027406,2.988280,0.296586
std,40616.735775,0.497439,12.384099,1.395493,1.736255,1.464466,1.321153,1.736255,5.617567,5.269328,0.499970,3.853615,1.413613,0.499993,0.385609,1.401842,1.396909,0.207030
min,0.000000,0.000000,18.000000,0.000000,0.000000,5.030000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,1.000000,0.000000
25%,35174.750000,0.000000,29.000000,0.000000,1.000000,6.290000,0.000000,1.000000,19.000000,7.000000,0.000000,3.000000,2.000000,0.000000,0.000000,2.000000,2.000000,0.133333
50%,70349.500000,0.000000,42.000000,0.000000,2.000000,7.770000,0.000000,2.000000,27.000000,15.000000,0.000000,6.000000,3.000000,0.000000,0.000000,3.000000,3.000000,0.275862
75%,105524.250000,1.000000,51.000000,0.000000,4.000000,8.920000,0.000000,4.000000,27.000000,20.000000,1.000000,10.000000,4.000000,1.000000,0.000000,4.000000,4.000000,0.421053
max,140699.000000,1.000000,60.000000,5.000000,5.000000,10.000000,5.000000,5.000000,35.000000,22.000000,1.000000,12.000000,5.000000,1.000000,1.000000,5.000000,5.000000,5.000000

In [17]:
test_data.describe()

,id,Gender,Age,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Work/Study Hours,Financial Stress,Pressure,Satisfaction,Work-Life Balance
count,93800.000000,93800.000000,93800.000000,93800.000000,93800.000000,18766.000000,93800.000000,93800.000000,93800.000000,93800.000000,93800.000000,93800.000000,93800.000000,93800.000000,93800.000000
mean,187599.500000,0.453497,40.321685,0.631951,2.408859,7.674016,0.588124,2.368294,22.636642,14.082249,6.247335,2.978763,3.041194,2.956674,0.295756
std,27077.871962,0.497835,12.393480,1.407628,1.740119,1.465056,1.326936,1.730696,5.629230,5.277973,3.858191,1.414604,1.401373,1.403460,0.217332
min,140700.000000,0.000000,18.000000,0.000000,0.000000,5.030000,0.000000,0.000000,-1.000000,-1.000000,0.000000,1.000000,1.000000,1.000000,-12.000000
25%,164149.750000,0.000000,29.000000,0.000000,1.000000,6.330000,0.000000,1.000000,19.000000,7.000000,3.000000,2.000000,2.000000,2.000000,0.133333
50%,187599.500000,0.000000,42.000000,0.000000,2.000000,7.800000,0.000000,2.000000,27.000000,15.000000,6.000000,3.000000,3.000000,3.000000,0.275862
75%,211049.250000,1.000000,51.000000,0.000000,4.000000,8.940000,0.000000,4.000000,27.000000,20.000000,10.000000,4.000000,4.000000,4.000000,0.421053
max,234499.000000,1.000000,60.000000,5.000000,5.000000,10.000000,5.000000,5.000000,35.000000,20.000000,12.000000,5.000000,6.000000,6.000000,9.000000

In [18]:
features = ['Gender', 'Age', 'Pressure', 'Satisfaction', 'Work/Study Hours', 'Financial Stress', 'Sleep Duration', 'Dietary Habits', 
        'Work-Life Balance']

In [19]:
X_train = train_data[features]
X_test = test_data[features]

y = train_data.Depression

In [20]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.callbacks import ReduceLROnPlateau

model = keras.Sequential([
    # First hidden layer
    layers.Dense(units=512, activation='relu', input_shape=[X_train.shape[1]]),
    layers.Dropout(0.5),  # Optional: Add dropout to reduce overfitting
    layers.BatchNormalization(),  # Optional: Add batch normalization
    
    # Second hidden layer
    layers.Dense(units=512, activation='relu'),
    layers.Dropout(0.5),  # Optional: Add dropout to reduce overfitting
    layers.BatchNormalization(),  # Optional: Add batch normalization
    
    # Third hidden layer
    layers.Dense(units=512, activation='relu'),
    layers.Dropout(0.5),  # Optional: Add dropout to reduce overfitting
    layers.BatchNormalization(),  # Optional: Add batch normalization
    
    # Output layer for binary classification
    layers.Dense(units=1, activation='sigmoid')  # For binary classification, use 'sigmoid'
])

/opt/conda/lib/python3.10/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [21]:
model.compile(optimizer='adam', 
              loss='binary_crossentropy', 
              metrics=['accuracy'])

In [22]:
lr_scheduler = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=3, min_lr=1e-6)

history = model.fit(
    X_train, y,
    batch_size=4096,
    epochs=10,
    callbacks=[lr_scheduler]
)

Epoch 1/10
35/35 ━━━━━━━━━━━━━━━━━━━━ 9s 183ms/step - accuracy: 0.7438 - loss: 0.6087 - learning_rate: 0.0010
Epoch 2/10

/opt/conda/lib/python3.10/site-packages/keras/src/callbacks/callback_list.py:96: UserWarning: Learning rate reduction is conditioned on metric `val_loss` which is not available. Available metrics are: accuracy,loss,learning_rate.
  callback.on_epoch_end(epoch, logs)

35/35 ━━━━━━━━━━━━━━━━━━━━ 11s 203ms/step - accuracy: 0.8927 - loss: 0.3497 - learning_rate: 0.0010
Epoch 3/10
35/35 ━━━━━━━━━━━━━━━━━━━━ 7s 189ms/step - accuracy: 0.8986 - loss: 0.2834 - learning_rate: 0.0010
Epoch 4/10
35/35 ━━━━━━━━━━━━━━━━━━━━ 7s 185ms/step - accuracy: 0.9018 - loss: 0.2553 - learning_rate: 0.0010
Epoch 5/10
35/35 ━━━━━━━━━━━━━━━━━━━━ 6s 184ms/step - accuracy: 0.9045 - loss: 0.2367 - learning_rate: 0.0010
Epoch 6/10
35/35 ━━━━━━━━━━━━━━━━━━━━ 7s 194ms/step - accuracy: 0.9054 - loss: 0.2302 - learning_rate: 0.0010
Epoch 7/10
35/35 ━━━━━━━━━━━━━━━━━━━━ 7s 209ms/step - accuracy: 0.9085 - loss: 0.2248 - learning_rate: 0.0010
Epoch 8/10
35/35 ━━━━━━━━━━━━━━━━━━━━ 7s 204ms/step - accuracy: 0.9078 - loss: 0.2233 - learning_rate: 0.0010
Epoch 9/10
35/35 ━━━━━━━━━━━━━━━━━━━━ 10s 196ms/step - accuracy: 0.9085 - loss: 0.2192 - learning_rate: 0.0010
Epoch 10/10
35/35 ━━━━━━━━━━━━━━━━━━━━ 7s 194ms/step - accuracy: 0.9083 - loss: 0.2185 - learning_rate: 0.0010

In [23]:
predictions = model.predict(X_test)
predictions_flat = predictions.reshape(-1)  # Ensure 1D
final = (predictions > 0.4).astype(int)
final_flat = final.reshape(-1)

2932/2932 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step

In [24]:
output = pd.DataFrame({
    'id': test_data['id'],  
    'Depression': final_flat
})

output.to_csv('mentalhealth_submission.csv', index=False)